### ISSUE TITLE
Failed to load build details

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#482]
```js
TypeError: Cannot read properties of undefined (reading 'map')
    at TaskExecutionInfo.tsx:123:34
    at si (react-dom.production.min.js:157:137)
    at Hi (react-dom.production.min.js:180:154)
    at $s (react-dom.production.min.js:269:343)
    at Cc (react-dom.production.min.js:250:347)
    at Rc (react-dom.production.min.js:250:278)
    at jc (react-dom.production.min.js:250:138)
    at yc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Wa (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at $a (react-dom.production.min.js:122:428)
    at hc (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at m.setState (react.production.min.js:12:369)
    at e._callback (ReactRelayFragmentContainer.js:61:15)
    at e._callback (RelayModernFragmentSpecResolver.js:70:15)
    at RelayModernFragmentSpecResolver.js:210:14
    at t._updateSubscription (RelayStoreSubscriptions.js:167:7)
    at RelayStoreSubscriptions.js:112:26
    at Set.forEach (<anonymous>)
    at t.updateSubscriptions (RelayStoreSubscriptions.js:111:25)
    at t.notify (RelayModernStore.js:301:30)
    at t.run (RelayPublishQueue.js:209:24)
    at t._runPublishQueue (OperationExecutor.js:1394:62)
    at t._handleNext (OperationExecutor.js:523:30)
    at OperationExecutor.js:343:16
    at e.exports (withDuration.js:27:16)
    at OperationExecutor.js:342:28
    at t._schedule (OperationExecutor.js:300:7)
    at t._next (OperationExecutor.js:341:10)
    at Object.next (OperationExecutor.js:157:17)
    at Object.next (RelayObservable.js:537:20)
    at Object.next (RelayObservable.js:190:40)
    at Object.next (RelayObservable.js:537:20)
    at RelayObservable.js:454:12
```

cc @fkorotkov - urgent

**Comment by fkorotkov** [comment]
What's the URL you see the issue on?

**Comment by RDIL** [comment]
Just saw it on https://cirrus-ci.com/task/5708723025346560 - it just happened for me like a second after the build completed - not sure exactly how to repro

**Comment by RDIL** [comment]
Regression of #473
