### ISSUE TITLE
I can't open my settings

### ISSUE THREAD

**Issue by ericoporto** [cirruslabs/cirrus-ci-web#575]
Hi, I can't seem to open my settings anymore (in `cirrus-ci.com/settings/github/ericoporto`), I have the following error on my JS Dev Console

```
instrument.ts:132 RelayNetwork: No data returned for operation `OwnerSettingsRendererQuery`, got error(s):
Validation error of type FieldUndefined: Field 'webhookURL' in type 'WebHookSettings' is undefined @ 'WebHookSettings_info/webhookSettings/webhookURL'
Validation error of type FieldUndefined: Field 'maskedSecretToken' in type 'WebHookSettings' is undefined @ 'WebHookSettings_info/webhookSettings/maskedSecretToken'

See the error `source` property for more information.
    at t (https://cirrus-ci.com/static/js/main.407f8eda.js:2:1051995)
    at Object.create (https://cirrus-ci.com/static/js/main.407f8eda.js:2:1052267)
    at https://cirrus-ci.com/static/js/main.407f8eda.js:2:960064
    at Array.forEach (<anonymous>)
    at t._handleErrorResponse (https://cirrus-ci.com/static/js/main.407f8eda.js:2:959825)
    at t._handleNext (https://cirrus-ci.com/static/js/main.407f8eda.js:2:960896)
    at https://cirrus-ci.com/static/js/main.407f8eda.js:2:959617
    at e.exports (https://cirrus-ci.com/static/js/main.407f8eda.js:2:1062449)
    at https://cirrus-ci.com/static/js/main.407f8eda.js:2:959601
    at t._schedule (https://cirrus-ci.com/static/js/main.407f8eda.js:2:959141)
    at t._next (https://cirrus-ci.com/static/js/main.407f8eda.js:2:959573)
    at Object.next (https://cirrus-ci.com/static/js/main.407f8eda.js:2:957339)
    at Object.next (https://cirrus-ci.com/static/js/main.407f8eda.js:2:938112)
    at Object.next (https://cirrus-ci.com/static/js/main.407f8eda.js:2:937165)
    at Object.next (https://cirrus-ci.com/static/js/main.407f8eda.js:2:938112)
    at https://cirrus-ci.com/static/js/main.407f8eda.js:2:939597
```

I have Google Chrome 117.0.5938.89 (Official version) 64 bits on Windows 10

**Comment by ericoporto** [comment]
It really fixed! Thanks!
